export const codes = {
  RESOURCE_CREATED: "RESOURCE_CREATED",
  RESOURCE_DELETED: "RESOURCE_DELETED",
  RESOURCE_UPDATED: "RESOURCE_UPDATED",
  INVALID_PARAMETERS: "INVALID_PARAMETERS",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  RESOURCE_FETCHED: "RESOURCE_FETCHED",
  RESOURCE_EXISTS: "RESOURCE_EXISTS",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED"
};
